routes/web.php
<?php

use App\Http\Controllers\Admin\BlogController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\GalleryController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\ImageController;
use App\Http\Controllers\Admin\NewsController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Client\MainController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('storage-link', function (){
    \Illuminate\Support\Facades\Artisan::call('storage:link');
});*/

Auth::routes();


Route::group(['middleware' => ['lang']], function () {
    Route::get('lang/{lang}', function ($lang) {
        session(['lang' => $lang]);
        return \Redirect::back();
    })->where([
        'lang' => 'en|es'
    ]);

    Route::get('', [MainController::class,'index'])->name('home');
});

Route::group(['prefix' => 'admin','middleware' => ['auth', 'lang']], function () {

    /*  Rutas de Administración */
    Route::get('', [HomeController::class, 'index'])->name('dashboard');
    Route::resource('/users', UserController::class)->except(['show']);
    Route::post('/users/active/{user}', [UserController::class, 'active'])->name('users.active');
    Route::resource('/categories', CategoryController::class);
    Route::post('/categories/active/{id}', [CategoryController::class, 'active'])->name('categories.active');
    Route::get('/categories/create/child/{parent_id}', [CategoryController::class, 'createChild'])->name('categories.createChild');
    Route::resource('/products', ProductController::class);
    Route::post('/products/active/{product}', [ProductController::class, 'active'])->name('products.active');
    Route::post('/products/new/{product}', [ProductController::class, 'new'])->name('products.new');
    Route::resource('/galleries', GalleryController::class);
    Route::post('/galleries/active/{gallery}', [GalleryController::class, 'active'])->name('galleries.active');
    Route::resource('/news', NewsController::class);
    Route::post('/news/active/{news}', [NewsController::class, 'active'])->name('news.active');
    Route::post('/blog/active/{blog}', [BlogController::class, 'active'])->name('blog.active');
    Route::resource('/blog', BlogController::class);
    Route::resource('/images', ImageController::class)->only(['store', 'destroy']);
});

app/Models/Gallery.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\Translatable\HasTranslations;

class Gallery extends Model
{
    use HasFactory, SoftDeletes, HasTranslations;

    protected $table = "galleries";

    protected $translatable = ['name', 'slug'];

    protected $fillable = [
        'name',
        'type',
        'reference',
        'active'
    ];
}

app/Http/Controllers/Admin/GalleryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Gallery;
use App\Models\Image;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\View;
use Illuminate\Support\Str as Str;

class GalleryController extends Controller
{
    protected $pages;
    protected $title;

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->title = "Galerias";
        $this->pages = 'gallery';

        View::share('title', $this->title);
        View::share('pages', $this->pages);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $galleries = Gallery::get();
        return view('admin.galleries.list', compact('galleries'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.galleries.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $gallery = Gallery::where('reference', 0)->where('type', 'general')->first();
        $data = $request->validate([
            'name' => 'required|string|min:3|max:250'
        ],[
            'name.required' => 'El campo nombre es obligatorio',
            'name.string' => 'El campo nombre debe ser una cadena de texto',
            'name.min' => 'El campo nombre debe tener minimo 3 caracteres',
            'name.max' => 'El campo nombre debe tener maximo 250 caracteres'
        ]);
        $gallery->name = $data['name'];
        $gallery->slug = Str::slug($data['name']);
        $gallery->save();

        return redirect(route('galleries.index'))->with('success', 'La galeria se creo con exito');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $gallery = Gallery::findOrFail($id);
        return view('admin.galleries.show', compact('gallery'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $gallery = Gallery::findOrFail($id);
        $images = Image::where('active', true)->where('gallery_id', $gallery->id)->get();
        return view('admin.galleries.edit', compact('gallery', 'images'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $gallery = Gallery::findOrFail($id);
        $data = $request->validate([
            'name' => 'required|string|min:3|max:250'
        ],[
            'name.required' => 'El campo nombre es obligatorio',
            'name.string' => 'El campo nombre debe ser una cadena de texto',
            'name.min' => 'El campo nombre debe tener minimo 3 caracteres',
            'name.max' => 'El campo nombre debe tener maximo 250 caracteres'
        ]);
        $gallery->name = $data['name'];
        $gallery->slug = Str::slug($data['name']);
        $gallery->save();

        return redirect(route('galleries.index'))->with('success', 'La galeria se creo con exito');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $gallery = Gallery::findOrFail($id);
        $gallery->delete();

        return redirect(route('galleries.index'))->with('success', 'La galeria se elimino correctamente');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function active($id)
    {
        $gallery = Gallery::findOrFail($id);
        if($gallery->active){
            $gallery->active = false;
            $result = 'desactivo';
        } else {
            $gallery->active = true;
            $result = 'activo';
        }
        $gallery->save();
        return redirect(route('galleries.index'))->with('success', 'La galeria se '. $result.' correctamente');
    }
}

resources/views/admin/galleries/create.blade.php
@extends('admin.layouts.app')

@section('title', 'Nueva Galeria')

@section('content')
    <div class="col-lg-12 px-md-5 bg-light mt-md-5">
        <div class="app-page-title">
            <div class="page-title-wrapper">
                <div class="page-title-heading">
                    <div class="page-title-icon">
                        <i class="fa fa-warehouse"></i>
                    </div>
                    <div>
                        Nueva Galeria
                        <div class="page-title-subheading">Agregar galeria.</div>
                    </div>
                </div>
                <div class="page-title-actions">
                    <a type="button" href="{{ route('galleries.index') }}" data-toggle="tooltip" title="Lista" data-placement="bottom" class="btn-shadow mr-3 btn btn-primary">
                        <i class="fa fa-list"></i>
                    </a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="main-card mb-3">
                    <div class="">
                        <form class="validate-form mb-5" method="POST" action="{{route('galleries.store')}}" enctype="multipart/form-data">
                            @csrf
                            <div class="row">
                                <div class="col-md-8">
                                    <div class="form-row">
                                        <div class="col-12">
                                            <div class="position-relative form-group">
                                                <label for="name">
                                                    @if(App::islocale('es'))
                                                        <img src="{{ asset('images/flags/Flag_of_mexico.png') }}" class="img-fluid" width="20px" alt="Spanish">
                                                    @endif
                                                    @if(App::islocale('en'))
                                                        <img src="{{ asset('images/flags/Flag_of_United.svg') }}" class="img-fluid" width="20px" alt="English">
                                                    @endif
                                                    Nombre
                                                </label>
                                                <input name="name" id="name" placeholder="Nombre" type="text" class="form-control" required value="{{ old('name') }}">
                                                @error('name')
                                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $message }}</strong>
                                                </span>
                                                @enderror
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row mt-3">
                                <div class="col-12">
                                    <div class="alert alert-info col-12" role="alert">
                                        <i class="fa fa-images"></i>
                                        Fotos (formato png, jpg o jpeg 1024 x 768 resolución 72 dpi )
                                    </div>
                                    <dropzone-component :reference="'0'" type="general"></dropzone-component>
                                </div>
                            </div>
                            <div class="row justify-content-end">
                                <div class="col-md-2">
                                    <button type="submit" class="btn btn-primary btn-block">
                                        <i class="fa fa-save"></i>
                                        Guardar
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/galleries/edit.blade.php
@extends('admin.layouts.app')

@section('title', 'Editar Galeria')

@section('content')
    <div class="col-lg-12 px-md-5 bg-light mt-md-5">
        <div class="app-page-title">
            <div class="page-title-wrapper">
                <div class="page-title-heading">
                    <div class="page-title-icon">
                        <i class="fa fa-warehouse"></i>
                    </div>
                    <div>
                        Editar Galeria
                        <div class="page-title-subheading">modificar galeria.</div>
                    </div>
                </div>
                <div class="page-title-actions">
                    <a type="button" href="{{ route('galleries.index') }}" data-toggle="tooltip" title="Lista" data-placement="bottom" class="btn-shadow mr-3 btn btn-primary">
                        <i class="fa fa-list"></i>
                    </a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="main-card mb-3">
                    <div class="">
                        <form class="validate-form mb-5" method="POST" action="{{route('galleries.update', ['gallery' => $gallery->id])}}" enctype="multipart/form-data">
                            @csrf
                            @method('PUT')
                            <div class="row">
                                <div class="col-md-8">
                                    <div class="form-row">
                                        <div class="col-12">
                                            <div class="position-relative form-group">
                                                <label for="name">
                                                    @if(App::islocale('es'))
                                                        <img src="{{ asset('images/flags/Flag_of_mexico.png') }}" class="img-fluid" width="20px" alt="Spanish">
                                                    @endif
                                                    @if(App::islocale('en'))
                                                        <img src="{{ asset('images/flags/Flag_of_United.svg') }}" class="img-fluid" width="20px" alt="English">
                                                    @endif
                                                    Nombre
                                                </label>
                                                <input name="name" id="name" placeholder="Nombre" type="text" class="form-control" required value="{{ old('name', $gallery->name) }}">
                                                @error('name')
                                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $message }}</strong>
                                                </span>
                                                @enderror
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row mt-3">
                                <div class="col-12">
                                    <div class="alert alert-info col-12" role="alert">
                                        <i class="fa fa-images"></i>
                                        Fotos (formato png, jpg o jpeg 1024 x 768 resolución 72 dpi )
                                    </div>
                                    <dropzone-component :reference="{{ $gallery->id }}" type="{{$gallery->type}}"></dropzone-component>
                                </div>
                            </div>
                            <div class="row justify-content-end">
                                <div class="col-md-2">
                                    <button type="submit" class="btn btn-primary btn-block">
                                        <i class="fa fa-save"></i>
                                        Actualizar
                                    </button>
                                </div>
                            </div>
                        </form>
                        <div class="row mb-5">
                            @if (session('success'))
                                <div class="alert alert-success alert-dismissible fade show" role="alert">
                                    <strong>{{ session('success') }}</strong>
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                            @endif
                            @foreach($images as $image)
                                <div class="col-12 col-sm-6 col-md-4 col-lg-3">
                                    <img src="{{asset($image->name)}}" class="img-fluid" alt="{{$image->name}}" id="logo">
                                    <form method="POST" action="{{ route('images.destroy', ['image' => $image->id]) }}">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn text-danger">
                                            <i class="fa fa-trash-alt"></i>
                                        </button>
                                    </form>
                                </div>
                            @endforeach
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/galleries/list.blade.php
@extends('admin.layouts.app')

@section('title', 'Lista de Galerias')

@section('content')
    <div class="col-lg-12 px-md-5 bg-light mt-md-5">
        <div class="app-page-title">
            <div class="page-title-wrapper">
                <div class="page-title-heading">
                    <div class="page-title-icon">
                        <i class="fa fa-images"></i>
                    </div>
                    <div>
                        Galerias
                        <div class="page-title-subheading">Agrega, Modifica, Elimina.</div>
                    </div>
                </div>
                <div class="page-title-actions">
                    <a type="button"  data-toggle="tooltip" title="Agregar" href="{{ route('galleries.create') }}" data-placement="bottom" class="btn-shadow mr-3 btn btn-primary">
                        <i class="fa fa-plus"></i>
                    </a>
                </div>
            </div>
        </div>
        @if (session('success'))
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <strong>{{ session('success') }}</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div
        @endif
        <div class="row mt-3">
            <div class="col-12">
                <div class="main-card mb-3">
                    <div class= table-responsive"><h5 class="card-title">Tabla de Galerias</h5>
                        <table class="mb-0 table table-hover mb-3">
                            <thead>
                            <tr>
                                <th>id</th>
                                <th>Nombre</th>
                                <th>Tipo</th>
                                <th class="text-center" colspan="2">Acciones</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($galleries->sortby('name') as $key => $gallery)
                                <tr>
                                    <td>
                                        {{ $key + 1 }}
                                    </td>
                                    <td>
                                        <a href="{{ route('galleries.edit', ['gallery' => $gallery->id]) }}" class="nav-link">
                                            @if($gallery->name)
                                                {{ $gallery->name }}
                                            @else
                                                Editar
                                            @endif
                                        </a>
                                    </td>
                                    <td>
                                        @switch($gallery->type)
                                            @case('categories')
                                                {{ __('Categorias') }}
                                            @break
                                            @case('products')
                                                {{ __('Productos') }}
                                            @break
                                            @case('blog')
                                                {{ __('Blog') }}
                                            @break
                                            @case('news')
                                                {{ __('Noticias') }}
                                            @break
                                            @default
                                                {{ __('Generico') }}
                                            @break
                                        @endswitch
                                    </td>
                                    <td width="50px">
                                        <form method="POST" action="{{ route('galleries.active', ['gallery' => $gallery->id]) }}">
                                            @csrf
                                            <button type="submit" class="btn">
                                                @if($gallery->active)
                                                    <i class="fa fa-power-off text-success"></i>
                                                @else
                                                    <i class="fa fa-power-off text-danger"></i>
                                                @endif
                                            </button>
                                        </form>
                                    </td>
                                    <td width="50px">
                                        <form method="POST" action="{{ route('galleries.destroy', ['gallery' => $gallery->id]) }}">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn text-danger">
                                                <i class="fa fa-trash-alt"></i>
                                            </button>
                                        </form></td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection