routes/web.php
<?php

use App\Http\Controllers\Admin\BlogController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\GalleryController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\ImageController;
use App\Http\Controllers\Admin\NewsController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Client\MainController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('storage-link', function (){
    \Illuminate\Support\Facades\Artisan::call('storage:link');
});*/

Auth::routes();


Route::group(['middleware' => ['lang']], function () {
    Route::get('lang/{lang}', function ($lang) {
        session(['lang' => $lang]);
        return \Redirect::back();
    })->where([
        'lang' => 'en|es'
    ]);

    Route::get('', [MainController::class,'index'])->name('home');
});

Route::group(['prefix' => 'admin','middleware' => ['auth', 'lang']], function () {

    /*  Rutas de Administración */
    Route::get('', [HomeController::class, 'index'])->name('dashboard');
    Route::resource('/users', UserController::class)->except(['show']);
    Route::post('/users/active/{user}', [UserController::class, 'active'])->name('users.active');
    Route::resource('/categories', CategoryController::class);
    Route::post('/categories/active/{id}', [CategoryController::class, 'active'])->name('categories.active');
    Route::get('/categories/create/child/{parent_id}', [CategoryController::class, 'createChild'])->name('categories.createChild');
    Route::resource('/products', ProductController::class);
    Route::post('/products/active/{product}', [ProductController::class, 'active'])->name('products.active');
    Route::post('/products/new/{product}', [ProductController::class, 'new'])->name('products.new');
    Route::resource('/galleries', GalleryController::class);
    Route::post('/galleries/active/{gallery}', [GalleryController::class, 'active'])->name('galleries.active');
    Route::resource('/news', NewsController::class);
    Route::post('/news/active/{news}', [NewsController::class, 'active'])->name('news.active');
    Route::post('/blog/active/{blog}', [BlogController::class, 'active'])->name('blog.active');
    Route::resource('/blog', BlogController::class);
    Route::resource('/images', ImageController::class)->only(['store', 'destroy']);
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\Translatable\HasTranslations;

class Category extends Model
{
    use HasFactory, SoftDeletes, HasTranslations;

    protected $table = "categories";

    protected $translatable = ['name', 'slug'];

    protected $fillable = [
        'name',
    ];

    public function children() {
        return $this->hasMany(Category::class, "parent_id", "id");
    }

    public function parent() {
        return $this->belongsTo(Category::class, "parent_id", "id");
    }

    public function recursiveChildren() {
        return $this->children()->with("recursiveChildren");
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Gallery;
use App\Models\Image;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\View;
use Illuminate\Support\Str as Str;

class CategoryController extends Controller
{

    protected $pages;
    protected $title;

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->title = "Categorias";
        $this->pages = 'category';

        View::share('title', $this->title);
        View::share('pages', $this->pages);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::whereNull('parent_id')->get();
        return view('admin.categories.list', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.categories.create');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param  int  $parent_id
     * @return \Illuminate\Http\Response
     */
    public function createChild($parent_id)
    {
        $category = Category::find($parent_id);
        return view('admin.categories.create', compact('parent_id', 'category'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->validate([
            'name' => 'required|string|min:3|max:250'
        ],[
            'name.required' => 'El campo nombre es obligatorio',
            'name.string' => 'El campo nombre debe ser una cadena de texto',
            'name.min' => 'El campo nombre debe tener minimo 3 caracteres',
            'name.max' => 'El campo nombre debe tener maximo 250 caracteres'
        ]);
        $category = new Category();
        $category->name = $data['name'];
        $category->slug = Str::slug($data['name']);
        $category->description = $request['description'];
        $category->parent_id = $request['parent_id'];
        $category->active = true;
        $image = $request->file('image');
        if($image) {
            $nameImage = time() . "_" . $image->getClientOriginalName();
            Storage::disk('public')->put('/images/categories/' . $nameImage, \File::get($image));
            $category->image = '/storage/images/categories/'.$nameImage;
        }
        $category->save();
        $galleries = Gallery::whereNull('reference')->where('type', 'categories')->get();
        if($galleries){
            for($i=0;count($galleries)>$i;$i++){
                $galleries[$i]->reference = $category->id;
                $galleries[$i]->save();
            }
        }
        return redirect(route('categories.index'))->with('success', '¡La categoria se creo con exito!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $categories = Category::    where('parent_id', $id)->get();
        return $categories;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::findOrFail($id);
        $gallery =  Gallery::where('active', true)->where('reference', $category->id)->where('type', 'categories')->first();
        $images = [];
        if ($gallery){
            $images = Image::where('gallery_id', $gallery->id)->get();
        }
        return view('admin/categories/edit', compact('category', 'images'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->validate([
            'name' => 'required|string|min:3|max:250'
        ],[
            'name.required' => 'El campo nombre es obligatorio',
            'name.string' => 'El campo nombre debe ser una cadena de texto',
            'name.min' => 'El campo nombre debe tener minimo 3 caracteres',
            'name.max' => 'El campo nombre debe tener maximo 250 caracteres'
        ]);
        $category = Category::findOrFail($id);
        $category->name = $data['name'];
        $category->slug = Str::slug($data['name']);
        $category->description = $request['description'];
        $category->parent_id = $request['parent_id'];
        $category->active = true;
        $image = $request->file('image');
        if($image) {
            $nameImage = time() . "_" . $image->getClientOriginalName();
            Storage::disk('public')->put('/images/categories/' . $nameImage, \File::get($image));
            $category->image = '/storage/images/categories/'.$nameImage;
        }
        $category->save();

        return redirect(route('categories.index'))->with('success', '¡La categoria se actualizo con exito!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::findOrFail($id);
        $category->delete();
        return redirect(route('categories.index'))->with('success', '¡La categoria se elimino con exito!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function active($id)
    {
        $category = Category::findOrFail($id);
        if($category->active){
            $category->active = false;
            $result = 'desactivo';
        } else {
            $category->active = true;
            $result = 'activo';
        }
        $category->save();
        return redirect(route('categories.index'))->with('success', 'La categoria se '. $result.' correctamente');
    }

}

resources/views/admin/categories/edit.blade.php
@extends('admin.layouts.app')

@section('title', isset($parent_id) == true ? 'Editar SubCategoria de la Categoria'. $categoryParent->name:'Editar Categoria')

@section('content')
    <div class="col-lg-12 px-md-5 bg-light mt-md-5">
        <div class="app-page-title">
            <div class="page-title-wrapper">
                <div class="page-title-heading">
                    <div class="page-title-icon">
                        <i class="fa fa-warehouse"></i>
                    </div>
                    <div>
                        Editar Categoria
                        <div class="page-title-subheading">Editar categoria.</div>
                    </div>
                </div>
                <div class="page-title-actions">
                    <a type="button" href="{{ route('categories.index') }}" data-toggle="tooltip" title="Lista" data-placement="bottom" class="btn-shadow mr-3 btn btn-primary">
                        <i class="fa fa-list"></i>
                    </a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="main-card mb-3 ">
                    <div class="">
                        <form class="validate-form mb-5" method="POST" action="{{route('categories.update', ['category' => $category->id])}}" enctype="multipart/form-data">
                            @csrf
                            @method('PUT')
                            @if(isset($parent_id))
                                <h5 class="card-title"><span class="text-info">Sub Categoria de la Categoria </span> {{ $categoryParent->name }}</h5>
                                <input type="hidden" name="parent_id" value="{{ $parent_id }}">
                            @endif
                            <div class="form-row">
                                <div class="col-12">
                                    <div class="position-relative form-group">
                                        <label for="name">
                                            @if(App::islocale('es'))
                                                <img src="{{ asset('images/flags/Flag_of_mexico.png') }}" class="img-fluid" width="20px" alt="Spanish">
                                            @endif
                                            @if(App::islocale('en'))
                                                <img src="{{ asset('images/flags/Flag_of_United.svg') }}" class="img-fluid" width="20px" alt="English">
                                            @endif
                                            Nombre
                                        </label>
                                        <input name="name" id="name" placeholder="Nombre" type="text" class="form-control" required value="{{ old('name', $category->name) }}">
                                    </div>
                                </div>
                            </div>
                            <div class="row mt-3">
                                <div class="col-12">
                                    <label for="">
                                        @if(App::islocale('es'))
                                            <img src="{{ asset('images/flags/Flag_of_mexico.png') }}" class="img-fluid" width="20px" alt="Spanish">
                                        @endif
                                        @if(App::islocale('en'))
                                            <img src="{{ asset('images/flags/Flag_of_United.svg') }}" class="img-fluid" width="20px" alt="English">
                                        @endif
                                        Descripción
                                    </label>
                                    <textarea class="ckeditor mt-3 @error('description') is-invalid @enderror bg-info" placeholder="Descripción"
                                              name="description" value="{{old('description', $category->description)}}">{{old('description', $category->description)}}</textarea>
                                    @error('description')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="row mt-5">
                                <div class="col-4">
                                    <label class="text-center">Imagen</label>
                                    <br>
                                    @if($category->image)
                                        <img src="{{asset($category->image)}}" class="img-fluid" alt="{{ $category->image }}" id="image">
                                    @else
                                        <img src="{{asset('images/missing.png')}}" class="img-fluid" alt="Sin imagen" id="image">
                                    @endif
                                </div>
                                <div class="col-8">
                                    <br><br>
                                    <div class="alert alert-primary" role="alert">
                                        <i class="fa fa-file-image"></i>
                                        Image (Formato png, jpg o jpeg 320 x 640 resolución 72 dpi max 900kb)<br>
                                    </div>

                                    <div class="upload-btn-wrapper" id="btnimage">
                                        <button class="btn btn-primary">Selecciona un archivo</button>
                                        <input type="file" name="image" accept="image/*" onchange="loadFileImage(event)">
                                    </div>
                                    <div id="deleteimage">
                                        <a class="btn btn-danger" onclick="deleteImage()">Eliminar Imagen</a>
                                    </div>
                                </div>
                            </div>
                            <div class="row mt-3">
                                <div class="col-12">
                                    <div class="alert alert-info col-12" role="alert">
                                        <i class="fa fa-images"></i>
                                        Fotos (formato png, jpg o jpeg 1024 x 768 resolución 72 dpi )
                                    </div>
                                    <dropzone-component :reference="'{{ $category->id }}'" type="categories"></dropzone-component>
                                </div>
                            </div>
                            <div class="row justify-content-end">
                                <div class="col-md-2">
                                    <button type="submit" class="btn btn-primary btn-block">
                                        <i class="fa fa-edit"></i>
                                        Actualizar
                                    </button>
                                </div>
                            </div>
                        </form>
                        <div class="row mb-5">
                            @if (session('success'))
                                <div class="alert alert-success alert-dismissible fade show" role="alert">
                                    <strong>{{ session('success') }}</strong>
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                            @endif
                            @foreach($images as $image)
                                <div class="col-12 col-sm-6 col-md-4 col-lg-3">
                                    <img src="{{asset($image->name)}}" class="img-fluid" alt="{{$image->name}}" id="logo">
                                    <form method="POST" action="{{ route('images.destroy', ['image' => $image->id]) }}">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn text-danger">
                                            <i class="fa fa-trash-alt"></i>
                                        </button>
                                    </form>
                                </div>
                            @endforeach
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @if($category->image)
            <script type="text/javascript"> var imageExist = true;</script>
        @else
            <script type="text/javascript"> var imageExist = false;</script>
        @endif
    </div>
@endsection
@section('scripts')
    <script type="text/javascript">
        if (imageExist){
            document.getElementById('btnimage').style.display = 'none';
            document.getElementById('deleteimage').style.display = 'block';
        } else {
            document.getElementById('btnimage').style.display = 'block';
            document.getElementById('deleteimage').style.display = 'none';
        }

        function deleteImage(){
            document.getElementById('deleteimage').style.display = 'none';
            document.getElementById('btnimage').style.display = 'block';
            var image = document.getElementById('image');
            image.src = '/images/missing.png';
            image.value = "";
        }

        var loadFileImage = function(event) {
            var reader = new FileReader();
            reader.onload = function(){
                var image = document.getElementById('image');
                image.src = reader.result;
            };
            reader.readAsDataURL(event.target.files[0]);
            document.getElementById('btnimage').style.display = 'none';
            document.getElementById('deleteimage').style.display = 'block';
        };
    </script>
@endsection

resources/views/admin/categories/list.blade.php
@extends('admin.layouts.app')

@section('title', 'Lista de Categorias')

@section('content')
    <div class="col-lg-12 px-md-5 bg-light mt-md-5">
        <div class="app-page-title">
            <div class="page-title-wrapper">
                <div class="page-title-heading">
                    <div class="page-title-icon">
                        <i class="fa fa-warehouse"></i>
                    </div>
                    <div>
                        Categorias
                        <div class="page-title-subheading">Agrega, Modifica, Elimina.</div>
                    </div>
                </div>
                <div class="page-title-actions">
                    <a type="button"  data-toggle="tooltip" title="Agregar" href="{{ route('categories.create') }}" data-placement="bottom" class="btn-shadow mr-3 btn btn-primary">
                        <i class="fa fa-plus"></i>
                    </a>
                </div>
            </div>
        </div>
        @if (session('success'))
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <strong>{{ session('success') }}</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div
        @endif
        <div class="row mt-3">
            <div class="col-12">
                <div class="main-card mb-3">
                    <div class=" table-responsive"><h5 class="card-title">Tabla de Categorias</h5>
                        @foreach($categories->sortby('name') as $key => $category)
                            <div class="row">
                                <div class="col-2">
                                    <a href="{{route('categories.edit', ['category' => $category->id])}}">
                                        @if($category->image)
                                            <img src="{{asset($category->image)}}" class="img-fluid" alt="{{$category->image}}" id="logo">
                                        @else
                                            <img src="{{asset('images/missing.png')}}" class="img-fluid" alt="Sin imagen" id="logo">
                                        @endif
                                    </a>
                                </div>
                                <div class="col-3">
                                    <a href="{{route('categories.edit', ['category' => $category->id])}}" class="nav-link text-dark">
                                        @if($category->name)
                                            {{ $category->name }}
                                        @else
                                            Editar
                                        @endif
                                    </a>
                                </div>
                                <div class="col-7">
                                    <div class="row justify-content-end">
                                        <a type="submit" class="btn" href="{{ route('categories.createChild', ['parent_id' => $category->id]) }}">
                                            <i class="fa fa-plus text-primary"></i>
                                        </a>
                                        <form method="POST" action="{{ route('categories.active', ['id' => $category->id]) }}">
                                            @csrf
                                            <button type="submit" class="btn">
                                                @if($category->active)
                                                    <i class="fa fa-power-off text-success"></i>
                                                @else
                                                    <i class="fa fa-power-off text-danger"></i>
                                                @endif
                                            </button>
                                        </form>
                                        <form method="POST" action="{{ route('categories.destroy', ['category' => $category->id]) }}">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn text-danger">
                                                <i class="fa fa-trash-alt"></i>
                                            </button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-12">
                                    <children-categories-component :parent_id="{{$category->id}}" :language="'{{ config('app.locale') }}'"></children-categories-component>
                                </div>
                            </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection