routes/web.php
<?php

use App\Http\Controllers\Admin\BlogController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\GalleryController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\ImageController;
use App\Http\Controllers\Admin\NewsController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Client\MainController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('storage-link', function (){
    \Illuminate\Support\Facades\Artisan::call('storage:link');
});*/

Auth::routes();


Route::group(['middleware' => ['lang']], function () {
    Route::get('lang/{lang}', function ($lang) {
        session(['lang' => $lang]);
        return \Redirect::back();
    })->where([
        'lang' => 'en|es'
    ]);

    Route::get('', [MainController::class,'index'])->name('home');
});

Route::group(['prefix' => 'admin','middleware' => ['auth', 'lang']], function () {

    /*  Rutas de Administración */
    Route::get('', [HomeController::class, 'index'])->name('dashboard');
    Route::resource('/users', UserController::class)->except(['show']);
    Route::post('/users/active/{user}', [UserController::class, 'active'])->name('users.active');
    Route::resource('/categories', CategoryController::class);
    Route::post('/categories/active/{id}', [CategoryController::class, 'active'])->name('categories.active');
    Route::get('/categories/create/child/{parent_id}', [CategoryController::class, 'createChild'])->name('categories.createChild');
    Route::resource('/products', ProductController::class);
    Route::post('/products/active/{product}', [ProductController::class, 'active'])->name('products.active');
    Route::post('/products/new/{product}', [ProductController::class, 'new'])->name('products.new');
    Route::resource('/galleries', GalleryController::class);
    Route::post('/galleries/active/{gallery}', [GalleryController::class, 'active'])->name('galleries.active');
    Route::resource('/news', NewsController::class);
    Route::post('/news/active/{news}', [NewsController::class, 'active'])->name('news.active');
    Route::post('/blog/active/{blog}', [BlogController::class, 'active'])->name('blog.active');
    Route::resource('/blog', BlogController::class);
    Route::resource('/images', ImageController::class)->only(['store', 'destroy']);
});

app/Models/News.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\Translatable\HasTranslations;

class News extends Model
{
    use HasFactory, SoftDeletes, HasTranslations;

    protected $table = "news";
    public $translatable = ['slug', 'title', 'intro', 'content'];

    public $fillable = ['title', 'intro', 'content', 'image', 'active', 'date'];
}

app/Http/Controllers/Admin/NewsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Gallery;
use App\Models\Image;
use App\Models\News;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\View;
use Illuminate\Support\Str as Str;

class NewsController extends Controller
{

    protected $pages;
    protected $title;

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->title = "Noticias";
        $this->pages = 'news';

        View::share('title', $this->title);
        View::share('pages', $this->pages);
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $newsAll = News::where('type', 'news')->get();
        return view('admin.news.list', compact('newsAll'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.news.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->validate([
            'title' => 'required',
            'intro' => 'required',
            'content' => 'required'
        ],[
            'title.required' => 'El campo titulo es obligatorio',
            'intro.required' => 'El campo introducción es obligatorio',
            'content.required' => 'El campo contenido es obligatorio',
        ]);
        $news = new News();
        $news->title = $data['title'];
        $news->slug = Str::slug($data['title']);
        $news->intro = $data['intro'];
        $news->content = $data['content'];
        $news->date = date_create('now');
        $news->type = 'news';
        $image = $request->file('image');
        if($image) {
            $nameImage = time() . "_" . $image->getClientOriginalName();
            Storage::disk('public')->put('/images/news/' . $nameImage, \File::get($image));
            $news->image = '/storage/images/news/'.$nameImage;
        }
        $news->save();
        $galleries = Gallery::whereNull('reference')->where('type', 'news')->get();
        if($galleries){
            for($i=0;count($galleries)>$i;$i++){
                $galleries[$i]->reference = $news->id;
                $galleries[$i]->save();
            }
        }

        return redirect(route('news.index'))->with('success', 'Se creo con exito la noticia');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $news = News::findOrFail($id);
        $gallery =  Gallery::where('active', true)->where('reference', $news->id)->where('type', 'news')->first();
        $images = [];
        if ($gallery){
            $images = Image::where('gallery_id', $gallery->id)->get();
        }
        return view('admin.news.edit', compact('news', 'images'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->validate([
            'title' => 'required',
            'intro' => 'required',
            'content' => 'required'
        ],[
            'title.required' => 'El campo titulo es obligatorio',
            'intro.required' => 'El campo introducción es obligatorio',
            'content.required' => 'El campo contenido es obligatorio',
        ]);
        $news = News::findOrFail($id);
        $news->title = $data['title'];
        $news->intro = $data['intro'];
        $news->content = $data['content'];
        $news->date = date_create('now');
        $image = $request->file('image');
        if($image) {
            $nameImage = time() . "_" . $image->getClientOriginalName();
            Storage::disk('public')->put('/images/news/' . $nameImage, \File::get($image));
            $news->image = '/storage/images/news/'.$nameImage;
        }
        $news->save();
        return redirect(route('news.index'))->with('success', 'Se actualizo con exito la noticia');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $news = News::findOrFail($id);
        $news->delete();
        return redirect(route('news.index'))->with('success', 'Se elimino con exito la noticia');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function active($id)
    {
        $news = News::findOrFail($id);
        if($news->active){
            $news->active = false;
            $result = 'desactivo';
        } else {
            $news->active = true;
            $result = 'activo';
        }
        $news->save();
        return redirect(route('news.index'))->with('success', 'La noticia se '. $result.' correctamente');
    }
}

resources/views/admin/news/edit.blade.php
@extends('admin.layouts.app')

@if($pages == 'news')
    @section('title', 'Editar Noticia')
@elseif($pages == 'blog')
    @section('title', 'Editar Blog')
@endif

@section('content')
    <div class="col-lg-12 px-md-5 bg-light mt-md-5">
        <div class="app-page-title">
            <div class="page-title-wrapper">
                <div class="page-title-heading">
                    <div class="page-title-icon">
                        <i class="fa fa-warehouse"></i>
                    </div>
                    <div>
                        @if($pages == 'news')
                            Editar Noticia
                        @elseif($pages == 'blog')
                            Editar Blog
                        @endif
                        <div class="page-title-subheading">
                            @if($pages == 'news')
                                Modificar Noticia
                            @elseif($pages == 'blog')
                                Modificar Blog
                            @endif
                        </div>
                    </div>
                </div>
                <div class="page-title-actions">
                    @if($pages == 'news')
                        <a type="button" href="{{ route('news.index') }}" data-toggle="tooltip" title="Lista" data-placement="bottom" class="btn-shadow mr-3 btn btn-primary">
                            <i class="fa fa-list"></i>
                        </a>
                    @elseif($pages == 'blog')
                        <a type="button" href="{{ route('blog.index') }}" data-toggle="tooltip" title="Lista" data-placement="bottom" class="btn-shadow mr-3 btn btn-primary">
                            <i class="fa fa-list"></i>
                        </a>
                    @endif
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="main-card mb-3 ">
                    <div class="">
                        @if($pages == 'news')
                            <form class="validate-form mb-5" method="POST" action="{{ route('news.update', ['news'=> $news->id]) }}" enctype="multipart/form-data">
                        @elseif($pages == 'blog')
                            <form class="validate-form mb-5" method="POST" action="{{ route('blog.update', ['blog'=> $news->id]) }}" enctype="multipart/form-data">
                        @endif
                                @method('PUT')
                                @csrf
                                <div class="row mt-5">
                                    <div class="col-12">
                                        <label for="">
                                            @if(App::islocale('es'))
                                                <img src="{{ asset('images/flags/Flag_of_mexico.png') }}" class="img-fluid" width="20px" alt="Spanish">
                                            @endif
                                            @if(App::islocale('en'))
                                                <img src="{{ asset('images/flags/Flag_of_United.svg') }}" class="img-fluid" width="20px" alt="English">
                                            @endif
                                            Titulo
                                        </label>
                                        <input type="text" class="form-control mt-3 @error('title') is-invalid @enderror" placeholder="Titulo" name="title" value="{{old('title', $news->title)}}">
                                        @error('title')
                                            <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                </div>
                                <div class="row mt-5">
                                    <div class="col-12">
                                        <label for="">
                                            @if(App::islocale('es'))
                                                <img src="{{ asset('images/flags/Flag_of_mexico.png') }}" class="img-fluid" width="20px" alt="Spanish">
                                            @endif
                                            @if(App::islocale('en'))
                                                <img src="{{ asset('images/flags/Flag_of_United.svg') }}" class="img-fluid" width="20px" alt="English">
                                            @endif
                                            Introducción
                                        </label>
                                        <textarea class="ckeditor mt-3 @error('intro') is-invalid @enderror" placeholder="Introducción"
                                                  name="intro" value="{{old('intro', $news->intro)}}">{{old('intro', $news->intro)}}</textarea>
                                        @error('intro')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                </div>
                                <div class="row mt-5">
                                    <div class="col-12">
                                        <label for="">
                                            @if(App::islocale('es'))
                                                <img src="{{ asset('images/flags/Flag_of_mexico.png') }}" class="img-fluid" width="20px" alt="Spanish">
                                            @endif
                                            @if(App::islocale('en'))
                                                <img src="{{ asset('images/flags/Flag_of_United.svg') }}" class="img-fluid" width="20px" alt="English">
                                            @endif
                                            Contenido
                                        </label>
                                        <textarea class="ckeditor mt-3 @error('content') is-invalid @enderror" placeholder="Contenido"
                                                  name="content" value="{{old('content', $news->content)}}">{{old('content', $news->content)}}</textarea>
                                        @error('content')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                </div>
                                <div class="row mt-5">
                                    <div class="col-4">
                                        <label class="text-center">Imagen</label>
                                        <br>
                                        <img src="{{asset('images/missing.png')}}" class="img-fluid" alt="Sin imagen" id="image">
                                    </div>
                                    <div class="col-8">
                                        <br><br>
                                        <div class="alert alert-primary" role="alert">
                                            <i class="fa fa-file-image"></i>
                                            Imagen (Formato png, jpg o jpeg 320 x 640 resolución 72 dpi max 900kb)<br>
                                        </div>

                                        <div class="upload-btn-wrapper" id="btnimage">
                                            <button class="btn btn-primary">Selecciona un archivo</button>
                                            <input type="file" name="image" accept="image/*" onchange="loadFileImage(event)">
                                        </div>
                                        <div id="deleteimage">
                                            <a class="btn btn-danger" onclick="deleteImage()">Eliminar Imagen</a>
                                        </div>
                                    </div>
                                </div>
                                <div class="row mt-3">
                                    <div class="col-12">
                                        <div class="alert alert-info col-12" role="alert">
                                            <i class="fa fa-images"></i>
                                            Fotos (formato png, jpg o jpeg 1024 x 768 resolución 72 dpi )
                                        </div>
                                        @if($pages == 'news')
                                            <dropzone-component :reference="{{ $news->id }}" type="news"></dropzone-component>
                                        @elseif($pages == 'blog')
                                            <dropzone-component :reference="{{ $news->id }}" type="blog"></dropzone-component>
                                        @endif

                                    </div>
                                </div>
                            <div class="row justify-content-end mt-3">
                                <div class="col-md-2">
                                    <button type="submit" class="btn btn-primary btn-block">
                                        <i class="fa fa-save"></i>
                                        Actualizar
                                    </button>
                                </div>
                            </div>
                        </form>
                       @foreach($images as $image)
                           <div class="col-12 col-sm-6 col-md-4 col-lg-3">
                               <img src="{{asset($image->name)}}" class="img-fluid" alt="{{$image->name}}" id="logo">
                               <form method="POST" action="{{ route('images.destroy', ['image' => $image->id]) }}">
                                   @csrf
                                   @method('DELETE')
                                   <button type="submit" class="btn text-danger">
                                       <i class="fa fa-trash-alt"></i>
                                   </button>
                               </form>
                           </div>
                       @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('scripts')
    <script type="text/javascript">
        document.getElementById('deleteimage').style.display = 'none';
        function deleteImage(){
            document.getElementById('deleteimage').style.display = 'none';
            document.getElementById('btnimage').style.display = 'block';
            var image = document.getElementById('image');
            image.src = '/images/missing.png';
            image.value = "";
        }

        var loadFileImage = function(event) {
            var reader = new FileReader();
            reader.onload = function(){
                var image = document.getElementById('image');
                image.src = reader.result;
            };
            reader.readAsDataURL(event.target.files[0]);
            document.getElementById('btnimage').style.display = 'none';
            document.getElementById('deleteimage').style.display = 'block';
        };
    </script>
@endsection

resources/views/admin/news/list.blade.php
@extends('admin.layouts.app')

@if($pages == 'news')
    @section('title', 'Lista de Noticias')
@elseif($pages == 'blog')
    @section('title', 'Lista de Blog')
@endif

@section('content')
    <div class="col-lg-12 px-md-5 bg-light mt-md-5">
        <div class="app-page-title">
            <div class="page-title-wrapper">
                <div class="page-title-heading">
                    <div class="page-title-icon">
                        <i class="fa fa-store"></i>
                    </div>
                    <div>
                        @if($pages == 'news')
                            Noticias
                        @elseif($pages == 'blog')
                            Blog
                        @endif
                        <div class="page-title-subheading">Agrega, Modifica, Elimina.</div>
                    </div>
                </div>
                <div class="page-title-actions">
                    @if($pages == 'news')
                        <a type="button"  data-toggle="tooltip" title="Agregar" href="{{ route('news.create') }}" data-placement="bottom" class="btn-shadow mr-3 btn btn-primary">
                            <i class="fa fa-plus"></i>
                        </a>
                    @elseif($pages == 'blog')
                        <a type="button"  data-toggle="tooltip" title="Agregar" href="{{ route('blog.create') }}" data-placement="bottom" class="btn-shadow mr-3 btn btn-primary">
                            <i class="fa fa-plus"></i>
                        </a>
                    @endif

                </div>
            </div>
        </div>
        @if (session('success'))
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <strong>{{ session('success') }}</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div
        @endif
        <div class="row mt-3">
            <div class="col-12">
                <div class="main-card mb-3 ">
                    <div class="table-responsive">
                        <h5 class="card-title">Tabla de
                            @if($pages == 'news')
                                Noticias
                            @elseif($pages == 'blog')
                                Blog
                            @endif
                        </h5>
                        <table class="mb-0 table table-hover mb-3">
                            <thead>
                            <tr>
                                <th>Imagen</th>
                                <th>Nombre</th>
                                <th>Introduccion</th>
                                <th>Fecha</th>
                                <th class="text-center" colspan="2">Acciones</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($newsAll->sortby('date') as $key => $news)
                                <tr>
                                    <td width="200px">
                                        @if($pages == 'news')
                                            <a href="{{route('news.edit', ['news' => $news->id])}}">
                                                @if($news->image)
                                                    <img src="{{asset($news->image)}}" class="img-fluid" alt="{{$news->image}}" id="poster">
                                                @else
                                                    <img src="{{asset('images/missing.png')}}" class="img-fluid" alt="Sin imagen" id="poster">
                                                @endif
                                            </a>
                                        @elseif($pages == 'blog')
                                            <a href="{{route('blog.edit', ['blog' => $news->id])}}">
                                                @if($news->image)
                                                    <img src="{{asset($news->image)}}" class="img-fluid" alt="{{$news->image}}" id="poster">
                                                @else
                                                    <img src="{{asset('images/missing.png')}}" class="img-fluid" alt="Sin imagen" id="poster">
                                                @endif
                                            </a>
                                        @endif
                                    </td>
                                    <td>
                                        @if($pages == 'news')
                                            <a href="{{route('news.edit', ['news' => $news->id])}}">
                                                @if($news->title)
                                                    {{$news->title}}
                                                @else
                                                    Editar
                                                @endif
                                            </a>
                                        @elseif($pages == 'blog')
                                            <a href="{{route('blog.edit', ['blog' => $news->id])}}">
                                                @if($news->title)
                                                    {{$news->title}}
                                                @else
                                                    Editar
                                                @endif
                                            </a>
                                        @endif
                                    </td>
                                    <td>{!! $news->intro !!}</td>
                                    <td>{{ \Carbon\Carbon::parse($news->date)->translatedFormat('l d F Y') }}</td>
                                    <td width="10px">
                                        @if($pages == 'news')
                                            <form method="POST" action="{{ route('news.active', ['news' => $news->id]) }}">
                                                @csrf
                                                <button type="submit" class="btn">
                                                    @if($news->active)
                                                        <i class="fa fa-power-off text-success"></i>
                                                    @else
                                                        <i class="fa fa-power-off text-danger"></i>
                                                    @endif
                                                </button>
                                            </form>
                                        @elseif($pages == 'blog')
                                            <form method="POST" action="{{ route('blog.active', ['blog' => $news->id]) }}">
                                                @csrf
                                                <button type="submit" class="btn">
                                                    @if($news->active)
                                                        <i class="fa fa-power-off text-success"></i>
                                                    @else
                                                        <i class="fa fa-power-off text-danger"></i>
                                                    @endif
                                                </button>
                                            </form>
                                        @endif
                                    </td>
                                    <td width="10px">
                                        @if($pages == 'news')
                                            <form method="POST" action="{{ route('news.destroy', ['news' => $news->id]) }}">
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit" class="btn text-danger">
                                                    <i class="fa fa-trash-alt"></i>
                                                </button>
                                            </form>
                                        @elseif($pages == 'blog')
                                            <form method="POST" action="{{ route('blog.destroy', ['blog' => $news->id]) }}">
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit" class="btn text-danger">
                                                    <i class="fa fa-trash-alt"></i>
                                                </button>
                                            </form>
                                        @endif
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection