routes/web.php
<?php

use App\Http\Controllers\Admin\BlogController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\GalleryController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\ImageController;
use App\Http\Controllers\Admin\NewsController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Client\MainController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('storage-link', function (){
    \Illuminate\Support\Facades\Artisan::call('storage:link');
});*/

Auth::routes();


Route::group(['middleware' => ['lang']], function () {
    Route::get('lang/{lang}', function ($lang) {
        session(['lang' => $lang]);
        return \Redirect::back();
    })->where([
        'lang' => 'en|es'
    ]);

    Route::get('', [MainController::class,'index'])->name('home');
});

Route::group(['prefix' => 'admin','middleware' => ['auth', 'lang']], function () {

    /*  Rutas de Administración */
    Route::get('', [HomeController::class, 'index'])->name('dashboard');
    Route::resource('/users', UserController::class)->except(['show']);
    Route::post('/users/active/{user}', [UserController::class, 'active'])->name('users.active');
    Route::resource('/categories', CategoryController::class);
    Route::post('/categories/active/{id}', [CategoryController::class, 'active'])->name('categories.active');
    Route::get('/categories/create/child/{parent_id}', [CategoryController::class, 'createChild'])->name('categories.createChild');
    Route::resource('/products', ProductController::class);
    Route::post('/products/active/{product}', [ProductController::class, 'active'])->name('products.active');
    Route::post('/products/new/{product}', [ProductController::class, 'new'])->name('products.new');
    Route::resource('/galleries', GalleryController::class);
    Route::post('/galleries/active/{gallery}', [GalleryController::class, 'active'])->name('galleries.active');
    Route::resource('/news', NewsController::class);
    Route::post('/news/active/{news}', [NewsController::class, 'active'])->name('news.active');
    Route::post('/blog/active/{blog}', [BlogController::class, 'active'])->name('blog.active');
    Route::resource('/blog', BlogController::class);
    Route::resource('/images', ImageController::class)->only(['store', 'destroy']);
});

resources/views/admin/components/footer.blade.php
<footer class="footer mt-auto py-3 bg-light">
    <div class="container">
        <span class="text-muted">Copyright © Todos los derechos reservados - Excess</span>
    </div>
</footer>

resources/views/admin/components/navbar.blade.php
<header class="navbar navbar-light sticky-top flex-md-nowrap" style="background-color: #fff;">
    <button class="navbar-toggler position-absolute d-md-none collapsed" id="btnopen" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <ul class="navbar-nav ml-md-auto my-2 my-md-0 me-md-3">
        <li class="nav-item dropdown">
            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                {{ Auth::user()->name }}
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{{ route('logout') }}"
                   onclick="event.preventDefault();
                                                            document.getElementById('logout-form').submit();">
                    {{ __('Salir') }}
                </a>
                <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                    @csrf
                </form>
            </div>
        </li>
    </ul>
</header>

resources/views/admin/components/sidebar.blade.php
<nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block sidebar collapse">
    <div class="row justify-content-between">
        <div>
            <a class="col-md-3 col-lg-2" href="{{route('dashboard')}}">
                <img src="{{ asset('images/logo.png') }}" class="img-fluid m-1" alt="Logo">
            </a>
        </div>
        <div class="pr-3">
            <button class="btn d-md-none ml-auto text-white " id="btnclose">
                <i class="fa fa-times"></i>
            </button>
        </div>
    </div>
    <div class="position-sticky pt-1">
        <ul class="nav flex-column">
            <li class="nav-item ">
                <span class="nav-link"><i class="fa fa-language"></i>
                    Estas Administrando en
                    @if (App::isLocale('en'))
                        Ingles
                    @elseif (App::isLocale('es'))
                        Español
                    @endif
                </span>
                @if (App::isLocale('en'))
                    <a class="nav-link text-white" href="{{ url('lang', ['es']) }}">
                        <span>Administra en</span>
                        <img src="{{ asset('images/flags/Flag_of_mexico.png') }}" width="20px" alt="spanish" style="cursor: pointer;">
                    </a>
                @elseif (App::isLocale('es'))
                    <a class="nav-link text-white" href="{{ url('lang', ['en']) }}">
                        <span>Administra en</span>
                        <img src="{{ asset('images/flags/Flag_of_United.svg') }}" width="20px" alt="english" style="cursor: pointer;">
                    </a>
                @endif
            </li>
            <li class="nav-item pt-3">
                <a class="nav-link {{ $pages == 'dashboard' ? 'active':'' }}" aria-current="page" href="{{ route('dashboard')}}">
                    <i class="fa fa-home"></i>
                    Home
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {{ $pages == 'user' ? 'active':'' }}" aria-current="page" href="{{ route('users.index')}}">
                    <i class="fa fa-users"></i>
                    Usuarios
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {{ $pages == 'category' ? 'active':'' }}" aria-current="page" href="{{ route('categories.index')}}">
                    <i class="fa fa-warehouse"></i>
                    Categorias
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {{ $pages == 'product' ? 'active':'' }}" aria-current="page" href="{{ route('products.index')}}">
                    <i class="fa fa-store-alt"></i>
                    Productos
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {{ $pages == 'gallery' ? 'active':'' }}" href="{{ route('galleries.index')}}">
                    <i class="fa fa-images"></i>
                    Galerias
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {{ $pages == 'news' ? 'active':'' }}" href="{{ route('news.index')}}">
                    <i class="fa fa-newspaper"></i>
                    Noticias
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {{ $pages == 'blog' ? 'active':'' }}" href="{{ route('blog.index')}}">
                    <i class="fa fa-blog"></i>
                    Blog
                </a>
            </li>

        </ul>
    </div>
</nav>

resources/views/admin/components/subcategories.blade.php
<div class="row">
    @foreach($categories->sortby('name') as $key => $category)
        {{ $category->name }}
    @endforeach
{{--    @include('admin.components.subcategories')--}}
</div>